name: Build & Release APK

on:
push:
branches:
- main
paths:
- 'lib/'
- 'android/'
- 'pubspec.yaml'

permissions:
contents: write

jobs:
build:
runs-on: ubuntu-22.04

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Cache Flutter & Pub
    uses: actions/cache@v4
    with:
      path: |
        ~/.pub-cache
        /opt/hostedtoolcache/flutter
      key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
      restore-keys: |
        ${{ runner.os }}-flutter-

  - name: Cache Gradle
    uses: actions/cache@v4
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      restore-keys: |
        ${{ runner.os }}-gradle-

  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17

  - name: Setup Flutter
    uses: subosito/flutter-action@v2
    with:
      flutter-version: 3.38.1
      cache: true

  - name: Install dependencies
    run: flutter pub get

  - name: Build APK
    run: flutter build apk --release --split-per-abi

  - name: Create or Update Release
    uses: softprops/action-gh-release@v2
    with:
      tag_name: latest
      name: Latest APK
      files: build/app/outputs/flutter-apk/app-*-release.apk
      draft: false
      prerelease: false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
